### ISSUE TITLE
User should be logged in automatically after clicking email confirmation link

### ISSUE THREAD

**Issue by lorddaedra** [pinax/django-user-accounts#130]
Please add ability to auto login after email confirmation if user is not authenticated and email was confirmed well...

**Comment by k4ml** [comment]
There should be a flag on this, since some people probably want to force user to login after verifying the email. Similar to django-allauth settings - ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION.

Pasting the notes from django-allauth here, just in case it also applied:-

>ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION (=False)
>The default behaviour is not log users in and to redirect them to ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL.
>
>By changing this setting to True, users will automatically be logged in once they confirm their email address. Note however that this only works when confirming the email address immediately after signing up, assuming users didn’t close their browser or used some sort of private browsing mode.

http://django-allauth.readthedocs.org/en/latest/configuration.html

**Comment by avelis** [comment]
🎉  @brosner Thanks for contributing this feature!
