### ISSUE TITLE
django.contrib.auth.models.User.account.RelatedObjectDoesNotExist: User has no account 

### ISSUE THREAD

**Issue by sinister-ghost** [pinax/django-user-accounts#345]
when i want to go to user settings : "django.contrib.auth.models.User.account.RelatedObjectDoesNotExist: User has no account"when i want to go to user settings
But everything else works. Registration, login, everything except an attempt to enter the profile settings.

**Comment by CourteousLion** [comment]
But everything else works. Registration, login, everything, except for a ride, go to the profile settings.

**Comment by jonathan-s** [comment]
Could you detail the exact replication steps for when this happens?

**Comment by toraritte** [comment]
Can't speak for @sinister-ghost, but this happened to us when upgrading an old Django app (Django 2.2.17, `django-user-accounts` 3.0.4, PostgreSQL 10.4) running in production to Django 4.2 and `django-user-accounts` 3.2.0. These are the steps in our case (although it is hard to give specifics given how outdated everything was...):

1. Upgrade `requirements.txt`
1. `pg_dump app_db > app_db.sql` on the production server
1. `psql -f app_db.sql` on dev server
1. `python lynx/manage.py migrate`
1. `psql --command="analyze"`

The codebase was not touched during all this. Serving the updated app worked, except for the error in the issue description when trying to log in with the right credentials.

For the record, the fix (in our case) was to simply insert rows to the `account_account` table linking to each user in the `auth_user` table.

```sql
SELECT id FROM auth_user WHERE username = 'my_username';  --> 27
INSERT INTO account_account(id, timezone, language, user_id) 
  VALUES (107,'','en', 27);
```

(Yeah, I'm neither a Python/Django nor a SQL whiz.)

The interesting thing is that in the outdated app, the logins worked, even though almost no user had a corresponding `account_account` entry. The [`django-user-accouns`](https://github.com/pinax/django-user-accounts/tree/master/account/migrations) migrations haven't changed since 2017(ish), so I'm almost sure that this issue has been introduced in Django 4. (Although, I couldn't make a full comparison between [Django 2.2.x `contrib/auth/migrations`](https://github.com/django/django/tree/stable/2.2.x/django/contrib/auth/migrations) and [Django 4.2.x `contrib/auth/migrations`](https://github.com/django/django/tree/stable/4.2.x/django/contrib/auth/migrations) yet.)

**Comment by uhurusurfa** [comment]
The error you saw (W042) seems to indicate seems to indicate that it thinks there was no primary key defined for the account_account model.
Can you share statement in the SQL dump file that creates the account_account table?

**Comment by Spawin** [comment]
Hi; I encounter this same error. It is caused by the absence of the account attribute at a user level. This is possible in my case because I added `django-user-accounts` to an existing project with users who do not have an associated account.

```python
# account.models.py
    @classmethod
    def for_request(cls, request):
        user = getattr(request, "user", None)
        if user and user.is_authenticated:
            account = user.account # <-- Error because a OneToOneField actually is a ForeignKey field with a unique=True constraint 
            # and a OneToOneField field does not mean that the referenced model always has account object(in your case). 
            # This is why in some case if user.account for some user not exists then it raises an RelatedObjectDoesNotExist.
            if account:
                return account
        return AnonymousAccount(request)
```

This can be solved with:

```python
# account.models.py
    @classmethod
    def for_request(cls, request):
        user = getattr(request, "user", None)
        if user and user.is_authenticated:
            account = getattr(user, "account", None)
            if account:
                return account
        return AnonymousAccount(request)
```

I can make a PR to propose this fix if this approach is accepted.

**Comment by uhurusurfa** [comment]
Looks good - Go ahead and raise a PR.
